title: Hack-a-Bot 2025
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://aj-floater.github.io/Hack

aux_links:
  Template Repository: https://github.com/aj-floater/Hack
